MaketManager/Controllers/ChoiceController.cs
using MaketManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaketManager.Controllers
{
    public class ChoiceController : Controller
    {
        //
        // GET: /Choice/

        [HttpPost]
        public ActionResult Output(MaketModel mm, string outputgen, string mailsend)
        {
            if (!string.IsNullOrEmpty(outputgen))
            {
                List<int> chosen = mm.Objects.Where(x => x.CheckedStatus == true).Select(z => z.Id).ToList();
                Models.MaketModel chsn = Session["FullMod"] as Models.MaketModel;
                Models.MaketModel mRes = new MaketModel();
                mRes.Objects = chsn.Objects.Select(x => x).Where(y => chosen.Contains(y.Id)).ToList();
                Tuple<DateTime, DateTime> daterange = Session["DateRange"] as Tuple<DateTime, DateTime>;

                string output = System.Web.Configuration.WebConfigurationManager.AppSettings["outputDir"];

                foreach (MaketRecipient mrc in mRes.Objects)
                {
                    string dirName = String.Format("{0}\\{1}", output, mrc.Performer);
                    Tool._MakeOutput(daterange.Item1, daterange.Item2, mrc, dirName);
                }

                return View();                
            }

            else
            {
                //determining selected objects and dates
                List<int> chosen = mm.Objects.Where(x => x.CheckedStatus == true).Select(z => z.Id).ToList();
                Models.MaketModel chsn = Session["FullMod"] as Models.MaketModel;
                Models.MaketModel mRes = new MaketModel();
                mRes.Objects = chsn.Objects.Select(x => x).Where(y => chosen.Contains(y.Id)).ToList();
                Tuple<DateTime, DateTime> daterange = Session["DateRange"] as Tuple<DateTime, DateTime>;

                foreach (MaketRecipient mrc in mRes.Objects)
                {
                    Mailsend.Send(mrc);
                }

                return View();
            }
            
        }

    }
}

MaketManager/Controllers/HomeController.cs
using MaketManager.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using MaketManager;

namespace BootstrapMvcSample.Controllers
{
    public class HomeController : BootstrapBaseController
    {
        public ActionResult Index()
        {
            List<SelectListItem> months = new List<SelectListItem> ();
            months.Add(new SelectListItem{Text="Январь",Value="1"});
            months.Add(new SelectListItem{Text="Февраль",Value="2"});
            months.Add(new SelectListItem{Text="Март",Value="3"});
            months.Add(new SelectListItem{Text="Апрель",Value="4"});
            months.Add(new SelectListItem{Text="Май",Value="5"});
            months.Add(new SelectListItem{Text="Июнь",Value="6"});
            months.Add(new SelectListItem{Text="Июль",Value="7"});
            months.Add(new SelectListItem{Text="Август",Value="8"});
            months.Add(new SelectListItem{Text="Сентябрь",Value="9"});
            months.Add(new SelectListItem{Text="Октябрь",Value="10"});
            months.Add(new SelectListItem{Text="Ноябрь",Value="11"});
            months.Add(new SelectListItem{Text="Декабрь",Value="12"});

            List<SelectListItem> years = new List<SelectListItem>();
            years.Add(new SelectListItem { Text = "2012", Value = "2012" });
            years.Add(new SelectListItem { Text = "2013", Value = "2013" });
            years.Add(new SelectListItem { Text = "2014", Value = "2014" });
            years.Add(new SelectListItem { Text = "2015", Value = "2015" });
            
            ViewBag.Month = months;
            ViewBag.Year = years;

            //Tool.TestCase();

            return View();
        }

        public ActionResult GetConfsList(string month, string year)
        {
            List<MaketRecipient> recipients = Tool._GetDirs(); 

            DateTime currentMonth = new DateTime();//начальная дата текущего месяца            
            DateTime.TryParse(month + "." + year, out currentMonth);
            DateTime nextMonth = currentMonth.AddMonths(1);//начальная дата следующего месяца
            
            List<Tuple<DateTime,DateTime>> days =Tool.PrepareDates(currentMonth, nextMonth); //список дней 
            

            //вычисление процента заполнения БД
            recipients.Select(x =>
            {                
                x.PointsList                    
                    .Select(y => 
                    {
                        Dictionary<string, double> cbd = new Dictionary<string, double>();
                        foreach (Tuple<DateTime,DateTime> pair in days)
                        {
                            double comp=Tool.CalculateCompleteness(pair.Item1, pair.Item2, y.AdapterId, 48,x.ConnString);
                            cbd.Add(pair.Item1.Day.ToString(),comp);
                        }
                        y.CompletenessByDay = cbd;
                        List<string> incompleteList = y.CompletenessByDay.Where(c => c.Value != 100.0).Select(c => c.Key).ToList();
                        y.CompByDayString = string.Join(", ",incompleteList);
                        y.OverallCompleteness = (int)y.CompletenessByDay.Values.Sum(val => val) / days.Count;
                        return y;
                    }).ToList();
                return x;
            }).ToList();

            recipients.Select(x =>
            {
                x.PointsList
                    .Select(y =>
                    {
                        y.ChannelsList
                            .Select(z =>
                            {
                                z.FirstValue = AccumValues.GetAccumulatedValue(currentMonth, x.ContractID, y.Code);
                                z.LastValue = AccumValues.GetAccumulatedValue(nextMonth, x.ContractID, y.Code);
                                if (z.FirstValue.Item2==z.LastValue.Item2)
                                {
                                    z.ConsumedAmount = Math.Round((z.Multiplier * z.LastValue.Item2 * (z.LastValue.Item1 - z.FirstValue.Item1)),4);    
                                }                                
                                return z;
                            }).ToList();
                        return y;
                    }).ToList();
                return x;
            }).ToList();

            
            MaketModel mm = new MaketModel();            
            mm.Objects = recipients;
            Session["FullMod"] = mm;
            Session["DateRange"] = new Tuple<DateTime,DateTime> (currentMonth,nextMonth);
            return View(mm);
        }

        

        

        

        

        
    }
}

MaketManager/Views/Home/GetConfList.cshtml
@{
    ViewBag.Title = "GetConfList";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

<h2>GetConfList</h2>

MaketManager/Views/Home/GetConfsList.cshtml
@model MaketManager.Models.MaketModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetConfsList</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/scripts/jquery-1.9.1.js"></script>
    <script src="~/scripts/bootstrap.js"></script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    @*<script src="~/scripts/getconfslist.js"></script>*@            
</head>
<body>
    <div class="container">
    <fieldset><legend style="text-align:center">Objects List</legend>
    @using (Html.BeginForm("Output", "Choice"))
    {
        for (int i = 0; i < Model.Objects.Count;i++ )
        {            
            <table class="table table-bordered">
                <caption>
                    @Html.CheckBoxFor(m => Model.Objects[i].CheckedStatus)                    
                    @Html.HiddenFor(m => Model.Objects[i].Id)
                    @Model.Objects[i].SenderName                                
                </caption>
                <thead>
                    <tr>
                        <th>Точка учета</th>
                        <th>Канал учета</th>
                        <th>Полнота данных по дням</th>
                        <th>Показания на начало периода</th>
                        <th>Показания на конец периода</th>
                        <th>Потребление</th>
                    </tr>
                </thead>
                
                @foreach (var point in Model.Objects[i].PointsList)
                {
                    foreach (var channel in @point.ChannelsList)
                    {   
                        <tr>                                
                            <td>
                                @point.Name                                
                            </td>
                            <td>
                                @channel.Name
                            </td>
                            @if (point.OverallCompleteness == 100)
                            {
                                <td>
                                    <div class="progress">                                            
                                                <div class="progress-bar bar-info" role="progressbar" aria-valuenow="@point.OverallCompleteness"
                                                     aria-valuemin="0" aria-valuemax="100" style="width:@point.OverallCompleteness%">
                                                    @point.OverallCompleteness% Complete                                                    
                                        </div>
                                                </div>
                                </td>                                
                            }

                            else
                            {
                                <td>                                   
                                    <div class="progress" data-toggle="tooltip" data-placement="top" title="Days containing incomplete data: @point.CompByDayString">
                                        <div class="progress-bar bar-warning" role="progressbar" aria-valuenow="@point.OverallCompleteness"
                                             aria-valuemin="0" aria-valuemax="100" style="width:@point.OverallCompleteness%">@point.OverallCompleteness% Complete</div>
                                        </div>
                                </td>                                
                            }                                
                            
                                @if (@channel.FirstValue.Item1>0)
                                {
                                    <td>
                                        @channel.FirstValue.Item1
                                    </td>                                    
                                }

                                else
                                {
                                    <td style="font-weight:bold;font-style:italic;color:#794044">
                                        @channel.FirstValue.Item1
                                    </td>    
                                }                            

                            @if (@channel.LastValue.Item1 > 0)
                            {
                                <td>
                                    @channel.LastValue.Item1
                                </td>
                            }

                            else
                            {
                                <td style="font-weight:bold;font-style:italic;color:#794044">
                                    @channel.LastValue.Item1
                                </td>
                            }
                            
                            
                            @if (@channel.ConsumedAmount > 0)
                            {
                                <td>
                                    @channel.ConsumedAmount
                                </td>
                            }
                            else
                            {
                                <td style="font-weight:bold;font-style:italic;color:#794044">
                                    @channel.ConsumedAmount
                                </td>
                            }
                        </tr>                        
                    }
                }            
             </table>
        }
        <input type="submit" class="btn btn-default" name="outputgen" id="outputgen" value="Generate output for checked" />
        <input type="submit" class="btn btn-default" name="mailsend" id="mailsend" value="Send emails for checked" />
    }
    </fieldset>
        
        </div>
</body>
</html>

MaketManager/Views/Home/Index.cshtml
@using MaketManager.Models
@using BootstrapSupport
@{
    Layout = "~/Views/shared/_BootstrapLayout.empty.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />        
</head>
<body>   

    @using (Html.BeginForm("GetConfsList", "Home", FormMethod.Post, new { id = "submitForm" }))
    { 
    <fieldset>
        @Html.DropDownList("Month")
        @Html.DropDownList("Year")
        <p>
            <input type="submit" class="btn btn-default" value="GetFilesList" />            
        </p>
    </fieldset>
    }
</body>
</html>